### ISSUE TITLE
MoH 731 KeyPops

### ISSUE THREAD

**Issue by mkaburu** [palladium-group/IQTools#16] opened 2017-11-22 20:27 UTC
3.4 Key POP Currently on ART
The list in tmp_Keypops has;
•	ClientsToSexWorkers,
•	DiscordantCouple,
•	MenWhoHaveSexWithMen
•	PeopleWhoInjectDrugs,
•	SexWorker
The new guidelines defines Keypos as
•	Mem who Have sex with men(MSM)
•	Female sex workers(FSW)
•	PeopleWhoInjectDrugs

**Comment by chris-githu** [comment] 2017-11-23 07:03
@mkaburu I'm not clear about what the issue is here.
Please elaborate.

Thanks.

**Comment by mkaburu** [comment] 2017-11-23 08:38
![keypops moh 731](https://user-images.githubusercontent.com/31726479/33164107-8050d0d0-d042-11e7-8b7a-65719b1fba00.PNG)

This is what should be picked as keypops as per the new definition in the MOH 731

**Comment by chris-githu** [comment] 2017-11-23 09:59
Closing this as is duplicate of #7

**Closed by chris-githu** 2017-11-23 09:59 UTC
Labels: query, report
